### ISSUE TITLE
Floating point default not being exposed

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrest#151]
Currently the floating point default is not being exposed via the json column description during schema introspection. I can verify that this is being set on the column properly in `ermrest` by querying the table itself.
```
float                         | real                     | default '1.6478'::real
float_disabled                | real                     | default '93.2182'::real
```

After submitting my form I can also verify the returned entity had the value set.

**Comment by karlcz** [comment]
This turned out to be a pretty obvious flaw in the existing code so I pushed a change that should fix it...

**Comment by jrchudy** [comment]
The changes made to the schema introspection to properly expose a float column’s default value worked. 

It did however cause columns with type `text`, `markdown`, `date`, and  `timestamp` to stop exposing their default values in the json schema. Although, they are still being set properly upon creation.

In each case, the introspection is returning `default: null` instead of the values in the table below.

```
 text                          | text                     | default 'default'::text
 text_disabled                 | text                     | default 'Disabled input'::text
 markdown                      | public.markdown          | default '**bold**'::text
 markdown_disabled             | public.markdown          | default '*italics*'::text
 date                          | date                     | default '2010-06-08'::date
 date_disabled                 | date                     | default '2014-05-12'::date
 timestamp                     | timestamp with time zone | default '2014-05-07 14:40:00-07'::timestamp with time zone
 timestamp_disabled            | timestamp with time zone | default '2010-06-13 17:22:00-07'::timestamp with time zone
```

**Comment by karlcz** [comment]
oops, sorry.  this should be fixed now and as a bonus I added support for json/jsonb column types which previously would throw an error when creating columns with defaults and would output an incorrect representation if the DBA had manually created such a column via SQL...

**Comment by karlcz** [comment]
@jrchudy  I pushed another fix to support domain types like `markdown` which I forgot to address in last fix...

**Comment by jrchudy** [comment]
I tested this out and see that _mostly_ everything is working as expected now. Markdown columns show a little more than the default value though. I still see the following from psql:
```
markdown                      | public.markdown          | default '**bold**'::text
markdown_disabled             | public.markdown          | default '*italics*'::text
```
which is good. Upon schema introspection, I see the same displayed for their default value:
```
{
    "comment": null, 
    "name": "markdown", 
    "default": "'**bold**'::text", 
    "nullok": true, 
    "type": {
      "typename": "markdown", 
      "is_domain": true, 
      "base_type": {
        "typename": "text"
      }
    }, 
    "annotations": {}
  }, 
  {
    "comment": null, 
    "name": "markdown_disabled", 
    "default": "'*italics*'::text", 
    "nullok": true, 
    "type": {
      "typename": "markdown", 
      "is_domain": true, 
      "base_type": {
        "typename": "text"
      }
    }, 
    "annotations": {
      "tag:isrd.isi.edu,2016:generated": null
    }
  }
```

**Comment by jrchudy** [comment]
I tested this and it all works as expected now. When @nitishksahu adds json column support, we will verify whether those defaults are working as expected or not.
