### ISSUE TITLE
Filters with columns equal to empty values are returning  400 Bad Request

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/ermrest#68]
ERROR: 400

    ResponseText: 400 Bad Request
    The request is malformed. URL parse error at token: LexToken(/,'/',1,74)
    TextStatus: error
    ErrorThrown: Bad Request
    URL: https://dev.rebuildingakidney.org/ermrest/catalog/1/aggregate/A:=rbk:v_image/$A/A1:=annotation/description=/$A/cnt:=cnt_d(id)

**Comment by karlcz** [comment]
I think this is now fixed in ermrest/master and new test cases added as well

**Comment by svoinea** [comment]
I'm still getting the error on rbk-dev which is doing hourly updates (at least the ~isrddev/ermrest directory has the latest).

Steps to test on rbk-dev:
 - Click "View all attributes"
 - Check "Annotation Description"
 - Click "ALL ATTRIBUTES"
 - Click "Annotation Description"
 - Check the box with the empty string

**Comment by karlcz** [comment]
Please re-test.  I don't think httpd gets restarted with the new ermrest codebase so the changes wasn't actually active.  We'll have to fix the hourly update separately to restart httpd...

**Comment by karlcz** [comment]
@svoinea can you confirm this is fixed now that the other rbk-dev hourly update issues have been resolved?

**Comment by svoinea** [comment]
Works as expected now.
