### ISSUE TITLE
Issue with aggregate API not considering the new union support for RBK in practice

### ISSUE THREAD

**Issue by chiragsanghvi** [informatics-isi-edu/ermrest#81]
### Aggregate 

Request
```
Request URL: https://dev.rebuildingakidney.org/ermrest/catalog/2/aggregate/A:=Resource:Protocol/$A/A2:=Protocol_Author/Author_Name=Han%20S.%20Chiu;Author_Name=Leif%20Oxburgh;Author_Name=Melissa%20H.%20Little;Author_Name=Minoru%20Takasato;Author_Name=Pei%20X.%20Er/$A/cnt:=cnt(*)
Request Method: GET
```
Response
```json
[{"cnt":5}]
```

### Entity 

Request
```
Request URL:https://dev.rebuildingakidney.org/ermrest/catalog/2/entity/A:=Resource:Protocol/$A/A2:=Protocol_Author/Author_Name=Han%20S.%20Chiu;Author_Name=Leif%20Oxburgh;Author_Name=Melissa%20H.%20Little;Author_Name=Minoru%20Takasato;Author_Name=Pei%20X.%20Er/$A
Request Method:GET
```
Response
```
[{"ID":1,"Title":"Generation of kidney organoids from human pluripotent stem cells","Version":"1.0","Abstract":"","Key":"Generation of kidney organoids from human pluripotent stem cells 1.0","Authors":"Leif Oxburgh","Subjects":"Cell biology","Keywords":"kidney; organoid; stem cell","Last_Modified":"2016-05-31T15:08:33.907927-07:00"},
 {"ID":2,"Title":"Protocol for the isolation and culture of CITED1+ nephron progenitor cells","Version":"1.0","Abstract":"Protocol","Key":"Protocol for the isolation and culture of CITED1+ nephron progenitor cells 1.0","Authors":"Leif Oxburgh","Subjects":"Cell biology","Keywords":null,"Last_Modified":"2016-05-31T15:08:33.907927-07:00"}]

```

As you observe that the `Aggregate API` returns the count as `5` for the join operation whereas the `Entity` API returns only `2` entities in response. 

I had a talk with @svoinea regarding this, and he said that this is because of the `union` change done by @karlcz to fix the `404` errors in `RBK`.

Shouldn't the same change be used for Aggregate API too ?

**Comment by svoinea** [comment]
The issue was fixed in Chaise through the commit 80b1a6cd658ea160fbb60d6f193765cd9f123a3f by replacing the `cnt(*)` function with `cnt_d(PK)` one.

It is ready for review on rbk-dev.

**Comment by chiragsanghvi** [comment]
It is still showing some inconsistency as the total number of records is not equal to the count.

![rbk](https://cloud.githubusercontent.com/assets/1658152/15763526/6758542a-28d9-11e6-83b3-ca47d467fcec.png)

**Comment by karlcz** [comment]
I don't think this is related to the disjunctive join condition enhancement and in fact is not a bug.

The aggregate count is not expected to equal the number of entities unless you use a distinct count on the entity key.  Both the aggregate and attributegroup APIs expose the pure inner join row set and let the client decide how to filter and or aggregate it.

By contrast, the entity and attribute APIs do an implicit DISTINCT ON reduction of the inner join row set to only produce one row per entity in the final entity path context of the whole ERMrest path expression.

**Comment by karlcz** [comment]
By the way here are relevant documentation bits:

- [Entity names](https://github.com/informatics-isi-edu/ermrest/blob/master/api-doc/data/naming.md#entity-names)
- [Aggregate names](https://github.com/informatics-isi-edu/ermrest/blob/master/api-doc/data/naming.md#aggregate-names)
- [Attribute grpup names](https://github.com/informatics-isi-edu/ermrest/blob/master/api-doc/data/naming.md#attribute-group-names)

Perhaps the aggregate names section is poorly worded or misleading?

**Comment by karlcz** [comment]
I just pushed an improvement to the aggregate API documentation. I hope this is now clear.
